# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Snappi 
email: team@snappi.io
description: > # this means to ignore newlines until "baseurl:"
  Through the standardization of microservice creation we can solve the
  problems they bring, further empower horizontal scaling, and empower
  service reuse like never before!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://snappi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: snappiteam
github_username:  snappi

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: false
gems:
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock

webserver_headers:
  "Access-Control-Allow-Origin": "*"
  "Server": "CustomServerName"

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: docs
    values:
      parent: null
      order: 0
